### ISSUE TITLE
a few hints for ubuntu users

### ISSUE THREAD

**Issue by andrewborell** [hajzer/bash-postfix-encrypt-filter#2]
Nice work. Not a lot of well-thought postfix implementations of pgp/smime like this for almost a decade. I think I would do a few things different on the exclusions lists for my sanity -- I'm thinking for my own ambitions maybe only encrypt if a matching gpg or smime exists instead of forcing it. Ill post back any code I add/remove or revise similar to my comments and notes below. 

Here are a few things I found that may help someone running postfix on ubuntu: 

need to create a home directory for the user. 
e.g. `_mkhomedir_helper bash-postfix-encrypt-filter_`

ubuntu used gawk and nawk depending on the verison but you can still install awk via the original-awk package
e.g. `_sudo apt install original-awk_`

some of the commands are "built-ins" as you can see in command line with type -a cmd_name. Aside from locating the correct path to the command this is also a good way to be sure that you have all the dependencies installed. 
e.g. `_type -a cd_ `

> SENDMAIL="/usr/sbin/sendmail -G -i" # NEVER NEVER NEVER use "-t" here. The -G option does nothing before Postfix 2.3.
> FORMAIL="/usr/bin/formail"
> **GPG="/usr/bin/gpg2"**
> DATE="/bin/date"
> **OPENSSL="/usr/bin/openssl"**
> **CD="cd"**
> CAT="/bin/cat"
> CP="/bin/cp"
> RM="/bin/rm"
> RMDIR="/bin/rmdir"
> **AWK="/usr/bin/awk"**
> MKDIR="/bin/mkdir"
> **ECHO="echo"**
> **PRINTF="printf"**
> **FIND="/usr/bin/find"**

Now to sort out how to decrypt in dovecot with the same toolbox and this will be an end-to-end solution.

**Comment by hajzer** [comment]
Thank you for your kind words and for the instructions for Ubuntu users ;-)
